import '@mediapipe/face_mesh/face_mesh.js';

const g = typeof window !== 'undefined' ? (window as any) : (globalThis as any);

export const FaceMesh = g.FaceMesh;
export const FACEMESH_FACE_OVAL = g.FACEMESH_FACE_OVAL;
export const FACEMESH_LIPS = g.FACEMESH_LIPS;
export const FACEMESH_LEFT_EYE = g.FACEMESH_LEFT_EYE;
export const FACEMESH_RIGHT_EYE = g.FACEMESH_RIGHT_EYE;
export const FACEMESH_LEFT_EYEBROW = g.FACEMESH_LEFT_EYEBROW;
export const FACEMESH_RIGHT_EYEBROW = g.FACEMESH_RIGHT_EYEBROW;
export const FACEMESH_LEFT_IRIS = g.FACEMESH_LEFT_IRIS;
export const FACEMESH_RIGHT_IRIS = g.FACEMESH_RIGHT_IRIS;
export const FACEMESH_CONTOURS = g.FACEMESH_CONTOURS;
export const FACEMESH_TESSELATION = g.FACEMESH_TESSELATION;

export default {
  FaceMesh: g.FaceMesh,
  FACEMESH_FACE_OVAL: g.FACEMESH_FACE_OVAL,
  FACEMESH_LIPS: g.FACEMESH_LIPS,
  FACEMESH_LEFT_EYE: g.FACEMESH_LEFT_EYE,
  FACEMESH_RIGHT_EYE: g.FACEMESH_RIGHT_EYE,
  FACEMESH_LEFT_EYEBROW: g.FACEMESH_LEFT_EYEBROW,
  FACEMESH_RIGHT_EYEBROW: g.FACEMESH_RIGHT_EYEBROW,
  FACEMESH_LEFT_IRIS: g.FACEMESH_LEFT_IRIS,
  FACEMESH_RIGHT_IRIS: g.FACEMESH_RIGHT_IRIS,
  FACEMESH_CONTOURS: g.FACEMESH_CONTOURS,
  FACEMESH_TESSELATION: g.FACEMESH_TESSELATION,
};
